name: null
favicon: null
layout_spectrum: 0.3855001060292125
typography_spectrum: 0.8917430760338902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1961061309557408
  lightness: 0.8563619845081121
  saturation: 0.5507630417123437
  rhythmicContrast: 0.25840604794211686
purpose: []
